-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  credits integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for user search history
create table user_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  id_video_youtube text not null references videos(id_video_youtube),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS for history
alter table user_history enable row level security;

create policy "Users can view own history." on user_history
  for select using (auth.uid() = user_id);

create policy "Users can insert own history." on user_history
  for insert with check (auth.uid() = user_id);

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, credits)
  values (new.id, new.email, 0);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
